-- MySQL Script generated by MySQL Workbench
-- dom 13 may 2018 22:32:21 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eegDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eegDB` ;

-- -----------------------------------------------------
-- Schema eegDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eegDB` DEFAULT CHARACTER SET utf8 ;
USE `eegDB` ;

-- -----------------------------------------------------
-- Table `eegDB`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`applications` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`applications` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `additional_info` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`django_content_type` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `model` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `eegDB`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `eegDB`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `eegDB`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `first_name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `last_name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(254) CHARACTER SET 'utf8' NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `eegDB`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`auth_user_user_permissions` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `eegDB`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`catalogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`catalogs` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`catalogs` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `accuracy` FLOAT NULL DEFAULT NULL,
  `classifier` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `energy_type` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `channels` INT(11) NULL DEFAULT NULL,
  `max_decomposition_level` INT(11) NULL DEFAULT NULL,
  `min_channel_length` INT(11) NULL DEFAULT NULL,
  `application_id` BIGINT(20) NULL DEFAULT NULL,
  `model` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_id1_idx` (`application_id` ASC),
  CONSTRAINT `app_id1`
    FOREIGN KEY (`application_id`)
    REFERENCES `eegDB`.`applications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`django_admin_log` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NOT NULL,
  `object_id` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `eegDB`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`django_migrations` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `applied` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`django_session` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`django_session` (
  `session_key` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `session_data` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `expire_date` DATETIME NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`health_check_db_testmodel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`health_check_db_testmodel` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`health_check_db_testmodel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`oauth2_provider_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`oauth2_provider_application` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`oauth2_provider_application` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `client_id` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `redirect_uris` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `client_type` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `authorization_grant_type` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `client_secret` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `skip_authorization` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `client_id` (`client_id` ASC),
  INDEX `oauth2_provider_application_client_secret_53133678` (`client_secret` ASC),
  INDEX `oauth2_provider_application_user_id_79829054_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `oauth2_provider_application_user_id_79829054_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`oauth2_provider_accesstoken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`oauth2_provider_accesstoken` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`oauth2_provider_accesstoken` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `expires` DATETIME NOT NULL,
  `scope` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `application_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `oauth2_provider_accesstoken_token_8af090f8_uniq` (`token` ASC),
  INDEX `oauth2_provider_accesstoken_user_id_6e4c9a65_fk_auth_user_id` (`user_id` ASC),
  INDEX `oauth2_provider_accesstoken_application_id_b22886e1_fk` (`application_id` ASC),
  CONSTRAINT `oauth2_provider_accesstoken_application_id_b22886e1_fk`
    FOREIGN KEY (`application_id`)
    REFERENCES `eegDB`.`oauth2_provider_application` (`id`),
  CONSTRAINT `oauth2_provider_accesstoken_user_id_6e4c9a65_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 346
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`oauth2_provider_grant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`oauth2_provider_grant` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`oauth2_provider_grant` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `expires` DATETIME NOT NULL,
  `redirect_uri` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `scope` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `application_id` BIGINT(20) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `oauth2_provider_grant_code_49ab4ddf_uniq` (`code` ASC),
  INDEX `oauth2_provider_grant_application_id_81923564_fk` (`application_id` ASC),
  INDEX `oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `oauth2_provider_grant_application_id_81923564_fk`
    FOREIGN KEY (`application_id`)
    REFERENCES `eegDB`.`oauth2_provider_application` (`id`),
  CONSTRAINT `oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`oauth2_provider_refreshtoken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`oauth2_provider_refreshtoken` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`oauth2_provider_refreshtoken` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `access_token_id` BIGINT(20) NOT NULL,
  `application_id` BIGINT(20) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `access_token_id` (`access_token_id` ASC),
  UNIQUE INDEX `oauth2_provider_refreshtoken_token_d090daa4_uniq` (`token` ASC),
  INDEX `oauth2_provider_refreshtoken_application_id_2d1c311b_fk` (`application_id` ASC),
  INDEX `oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `oauth2_provider_refreshtoken_access_token_id_775e84e8_fk`
    FOREIGN KEY (`access_token_id`)
    REFERENCES `eegDB`.`oauth2_provider_accesstoken` (`id`),
  CONSTRAINT `oauth2_provider_refreshtoken_application_id_2d1c311b_fk`
    FOREIGN KEY (`application_id`)
    REFERENCES `eegDB`.`oauth2_provider_application` (`id`),
  CONSTRAINT `oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eegDB`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `eegDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eegDB`.`users` ;

CREATE TABLE IF NOT EXISTS `eegDB`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `app_id` BIGINT(20) NULL DEFAULT NULL,
  `username` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_id2_idx` (`app_id` ASC),
  CONSTRAINT `app_id2`
    FOREIGN KEY (`app_id`)
    REFERENCES `eegDB`.`applications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
